# **Grundlagen NumPy**

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
matrix = [[1,2,3],[4,5,6]]

In [6]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.linspace(0,11,10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(4)

array([0.70802889, 0.37574678, 0.93830146, 0.20988281])

In [22]:
np.random.rand(4,4)

array([[0.96601683, 0.86671128, 0.17081747, 0.08294133],
       [0.39113289, 0.41778594, 0.98052943, 0.40829191],
       [0.58438806, 0.00809029, 0.10240103, 0.52484666],
       [0.77144237, 0.67561278, 0.56670033, 0.61080511]])

In [35]:
np.random.randint(1,100)

27

In [47]:
np.random.randint(1,100,10)

array([34, 42, 39, 28, 85, 46,  1, 55, 93, 44], dtype=int32)

In [59]:
arr = np.arange(25)

In [61]:
ranarr = np.random.randint(0,50,10)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [62]:
ranarr

array([10, 31,  7, 17, 26, 10, 27, 40,  2, 29], dtype=int32)

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
ranarr

array([10, 31,  7, 17, 26, 10, 27, 40,  2, 29], dtype=int32)

In [64]:
ranarr.max()

np.int32(40)

In [65]:
ranarr.argmax()

np.int64(7)

In [66]:
ranarr.min()

np.int32(2)

In [67]:
ranarr.argmin()

np.int64(8)

In [ ]:
# shape ist ein Attrribut und keine Methode und deshalb werden auch keine Klammern gesetzt

arr.shape

(25,)

In [69]:
ranarr.shape

(10,)

In [72]:
arr.dtype

dtype('int64')

In [73]:
ranarr.dtype

dtype('int32')

# **Numpy Indizierung**
## NumPy Indexing und Selectionr

In [74]:
import numpy as np

In [75]:
arr = np.arange(0,11)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr[8]

np.int64(8)

In [80]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [81]:
# NumPy Broadcasting

arr[0:5] = 100

In [82]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [83]:
# Array wieder zurücksetzen

arr = np.arange(0,11)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
teil_arr = arr[0:6]

In [87]:
teil_arr

array([0, 1, 2, 3, 4, 5])

In [88]:
teil_arr[:]=99

In [89]:
teil_arr

array([99, 99, 99, 99, 99, 99])

In [91]:
# Ergebnis: das Ursprungsarray wurde auch geändert mit 99
# array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
# Kopie von arr erstellen

arr_kopie = arr.copy()

In [93]:
arr_kopie

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [94]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [95]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [98]:
# indexieren

arr_2d[0]

array([ 5, 10, 15])

In [99]:
arr_2d[2]

array([35, 40, 45])

In [101]:
arr_2d[0][0]

np.int64(5)

In [104]:
#vereinfacchte Schreibweise
arr_2d[0,0]

np.int64(5)

In [105]:
# Alle ELemente bis 2 (2 ist exklusiv)
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [106]:
# Alle ELemente bis 2 (2 ist exklusiv)
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [107]:
arr_2d[2]

array([35, 40, 45])

In [108]:
arr_2d[2,:]

array([35, 40, 45])

# Selection

In [109]:
arr = np.arange(1,11)

In [110]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [112]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [114]:
# Alle Werte die True sind bzw größer 5 sind ausgeben
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
# Dem Arr das Arr übergeben und die Bedinung (arr>5)
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [116]:
x=2
arr[arr<x]

array([1])

## Aufgabe: gebe vom nachfolgendem arr_2d die Werte 13 und oder 14 und oder 23 und oder 24

In [119]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [120]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
# Lösung 

arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# **NumPy Operations**

In [122]:
import numpy as np

In [123]:
arr = np.arange(0,10)

In [124]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [127]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [128]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warnung bei 0 / 0: Wert NaN wird zurückgegeben

arr / arr

C:\Users\bedla\AppData\Local\Temp\ipykernel_12788\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Warnung: eine Zahl durch 0 ergibt inf (unendlich)

1/arr

C:\Users\bedla\AppData\Local\Temp\ipykernel_12788\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [131]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [133]:
# quadratwurzel ziehen

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# Exponenten
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [135]:
np.max(arr)

np.int64(9)

In [136]:
arr.max()

np.int64(9)

In [137]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# Log 0 kann nicht berechnet werden und es wird inf (unendlich) ausgegeben 

np.log(arr)

C:\Users\bedla\AppData\Local\Temp\ipykernel_12788\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Aufgaben zur Wiederholung

- Erstelle ein Array von 10 Nullen

- Erstelle ein Array von 10 Einsen

- Erstelle ein Array von 10 Fünfen

- Erstelle ein Array der Zahlen von 10 bis 50

- Erstelle ein Array aller Zahlen zwischen 10 bis 50

- Erstelle ein Array aller geraden Zahlen zwischen 10 bis 50

- Erstelle eine Matrix 3x3, die die Zahlen von 0 bis 8 beinhaltet

- Erstelle eine 3x3 Einheitsmatrix

- Nutze NumPy, um eine Zufallszahl zwischen 0 und 1 zu erstellen

- Nutze NumPy, um ein Array von 25 Zufallszahlen, die einer Standardnormalverteilung folgen, zu erstellen.

- Erstelle eine 10x10 Matrix mit den Zahlen von 0 bis 1 (geordnet)

- Erstelle ein Array aus 20 gleichmäßig verteilten Punkten zwischen 0 und 1

![alt text](5195327149052131846.jpg)

![alt text](5195327149052131855.jpg)

![alt text](5195327149052131859.jpg)

![alt text](5195327149052131862.jpg)