# Coding Exercises (Appendix 3)

Now, you will have the opportunity to practice what you have learned. <br>
__Follow the instructions__ and insert your code! 

The correct answer is provided below your coding cell. There you can check whether your code is correct.

If you need some help or if you want to check your code, you can also have a look at the __solutions__.

### Have Fun!

--------------------------------------------------------------------------------------------------------------

## Exercise 7: The Numpy Package: Working with numbers made easy!

1. Import Numpy!

In [2]:
import numpy as np

2. You have the following stock Prices in EUR Currency : [23.65, 43.21, 73.01, 87.32]<br>

Create a __Numpy array__ and __convert all prices__ to USD Currency @ an fx rate of __1.2__ (1.2 USD per 1 EUR).

In [4]:
stock_eur=np.array([23.65, 43.21, 73.01, 87.32])
stock_eur

array([23.65, 43.21, 73.01, 87.32])

In [8]:
stock_usd=stock_eur*1.2


(result: array([ 28.38 ,  51.852,  87.612, 104.784])

In [7]:
stock_usd

array([ 28.38 ,  51.852,  87.612, 104.784])

You have the 
- end-of-2017 stock prices for four companies: [33.65, 63.21, 53.01, 17.32]
- end-of-2018 stock prices for the same companies: [36.54, 61.59, 60.31, 10.40]

3. Calculate the __absolute__ price increase / decrease in 2018 __for all four companies__. Use __vectorized__ numpy code!

In [9]:
stock_2017=np.array([33.65, 63.21, 53.01, 17.32])
stock_2018=np.array([36.54, 61.59, 60.31, 10.40])

In [10]:
price_changes=stock_2018-stock_2017
price_changes

array([ 2.89, -1.62,  7.3 , -6.92])

In [27]:
returns=price_changes/stock_2017


4. Calculate the __price return__ in 2018 __for all four companies__. Use __vectorized__ numpy code!

In [28]:
returns

array([ 0.0858841 , -0.02562886,  0.13770987, -0.39953811])

You have the following list with cashflows (starting today at t0): [-500, -100, 200, 600, 1000, 800]

In [29]:
#run the cell!
l  = [-500, -100, 200, 600, 1000, 800]

5. Convert l into a __numpy array__ and __save__ the array in memory! __Select__ the __second cashflow__ at t1.

In [30]:
array=np.array(l)

In [31]:
array[1]

np.int64(-100)

6. __Slice__ the array for the __last two cashflows__!

In [36]:
array[-2:]

array([1000,  800])

7. __Slice__ the array for the cashflows in __t2, t3 and t4__.

In [41]:
array[[2,3,4]]

array([ 200,  600, 1000])

The ABC Company evaluates to buy an additional machine that will increase future profits/cashflows by
- 50 USD in t1, 
- 80 USD in t2,
- 120 USD in t3, 
- 150 USD in t4,
- 200 USD in t5. (each cf at period´s end)<br>

8. The machine costs 500 USD (Investment in to). Calculate the __Project´s NPV__ and evaluate whether ABC should pursue the project. <br> ABC´s required rate of return (Cost of Capital) is 7.5% p.a. Use __vectorized__ numpy code!

In [71]:
# run the cell
cf = np.array([-500, 50, 80, 120, 150, 200])
cf

array([-500,   50,   80,  120,  150,  200])

In [72]:
n=np.array([0,1,2,3,4,5])
n

array([0, 1, 2, 3, 4, 5])

In [73]:
r=0.075
f=1+r

(result: -36.03468883756554 -> no!)

In [74]:
npv=cf/f**n
npv

array([-500.        ,   46.51162791,   69.22660898,   96.59526834,
        112.32007947,  139.31172647])

9. __Slice__ the array cf (from question 8) for the positive inflows (__from t1__) and __save__ the slice in the __variable cf_pos__. <br> Make sure that once you __change the slice cf_pos__, the array __cf shall change as well__!

In [75]:
cf_pos=cf[1:]
cf_pos

array([ 50,  80, 120, 150, 200])

10. Change the first cashflow (t1) of __cf_pos to 70__. Check whether __cf gets mutated as well__!

In [76]:
cf_pos[0]=70
cf_pos

array([ 70,  80, 120, 150, 200])

In [77]:
cf

array([-500,   70,   80,  120,  150,  200])

11. __Restore cf__ and __redo Q9 and Q10__. This time make sure that cf and cf_pos are __independent objects__! 

In [81]:
cf = np.array([-500, 50, 80, 120, 150, 200])
cf

array([-500,   50,   80,  120,  150,  200])

In [82]:
cf_pos=cf[1:].copy()
cf_pos

array([ 50,  80, 120, 150, 200])

In [83]:
cf_pos[0]=70
cf_pos

array([ 70,  80, 120, 150, 200])

In [84]:
cf

array([-500,   50,   80,  120,  150,  200])

12. Calculate the __total sum__ over all cashflows of cf!

In [ ]:
# run the cell
cf = np.array([-500, 50, 80, 120, 150, 200])
cf

In [85]:
cf.sum()

np.int64(100)

13. Return the __highest Value__ of cf!

In [86]:
cf.max()

np.int64(200)

14. Calculate the __cumulative cashflows__ for cf!

In [91]:
cf.cumsum()


array([-500, -450, -370, -250, -100,  100])

15. Assume the following list: [3, 10, 6, 45, 100]. Calculate the __square root__ for all elements in the list. 

In [95]:
l=np.array([3, 10, 6, 45, 100])
type(l)

numpy.ndarray

In [96]:
np.sqrt(l)

array([ 1.73205081,  3.16227766,  2.44948974,  6.70820393, 10.        ])

Assume the following stock prices:

In [97]:
# run the cell!
a = np.array([0.34, 43.56, 32.12, 67.43, 0.87, 9.87])
a

array([ 0.34, 43.56, 32.12, 67.43,  0.87,  9.87])

16. __Filter__ a for all penny stocks! (price less than 1)

In [100]:
filter2=a[a<1]
filter2

array([0.34, 0.87])

(result: array([0.34, 0.87]))

# Well Done!

# Solutions (Stop here if you want to code on your own!)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

1. Import Numpy!

In [ ]:
import numpy as np

2. You have the following stock Prices in EUR Currency : [23.65, 43.21, 73.01, 87.32]<br>

Create a __Numpy array__ and __convert all prices__ to USD Currency @ an fx rate of __1.2__ (1.2 USD per 1 EUR).

In [ ]:
a = np.array([23.65, 43.21, 73.01, 87.32])
a

In [ ]:
a * 1.2

(result: array([ 28.38 ,  51.852,  87.612, 104.784])

You have the 
- end-of-2017 stock prices for four companies: [33.65, 63.21, 53.01, 17.32]
- end-of-2018 stock prices for the same companies: [36.54, 61.59, 60.31, 10.40]

3. Calculate the __absolute__ price increase / decrease in 2018 __for all four companies__. Use __vectorized__ numpy code!

In [23]:
p_2017 = np.array([33.65, 63.21, 53.01, 17.32])
p_2018 = np.array([36.54, 61.59, 60.31, 10.40])

In [24]:
p_2018 - p_2017

array([ 2.89, -1.62,  7.3 , -6.92])

4. Calculate the __price return__ in 2018 __for all four companies__. Use __vectorized__ numpy code!

In [25]:
(p_2018 / p_2017) -1 

array([ 0.0858841 , -0.02562886,  0.13770987, -0.39953811])

You have the following list with cashflows (starting today at t0): [-500, -100, 200, 600, 1000, 800]

In [ ]:
#run the cell!
l  = [-500, -100, 200, 600, 1000, 800]

5. Convert l into a __numpy array__ and __save__ the array in memory! __Select__ the __second cashflow__ at t1.

In [ ]:
a = np.array(l)
a

In [ ]:
a[1]

6. __Slice__ the array for the __last two cashflows__!

In [ ]:
a[-2:]

7. __Slice__ the array for the cashflows in __t2, t3 and t4__.

In [ ]:
a[2:5]

The ABC Company evaluates to buy an additional machine that will increase future profits/cashflows by
- 50 USD in t1, 
- 80 USD in t2,
- 120 USD in t3, 
- 150 USD in t4,
- 200 USD in t5. (each cf at period´s end)<br>

In [ ]:
# run the cell
cf = np.array([-500, 50, 80, 120, 150, 200])
cf

8. The machine costs 500 USD (Investment in to). Calculate the __Project´s NPV__ and evaluate whether ABC should pursue the project. <br> ABC´s required rate of return (Cost of Capital) is 7.5% p.a. Use __vectorized__ numpy code!

In [ ]:
r = 0.075
f = 1 + r

In [ ]:
n = np.array([0, 1, 2, 3, 4, 5])
n

In [ ]:
(cf / f**n).sum()

(result: -36.03468883756554 -> no!)

9. __Slice__ the array cf (from question 8) for the positive inflows (__from t1__) and __save__ the slice in the __variable cf_pos__. <br> Make sure that once you __change the slice cf_pos__, the array __cf shall change as well__!

In [ ]:
cf_pos = cf[1:]
cf_pos

10. Change the first cashflow (t1) of __cf_pos to 70__. Check whether __cf gets mutated as well__!

In [ ]:
cf_pos[0] = 70

In [ ]:
cf

11. __Restore cf__ and __redo Q9 and Q10__. This time make sure that cf and cf_pos are __independent objects__! 

In [ ]:
cf = np.array([-500, 50, 80, 120, 150, 200])
cf

In [ ]:
cf_pos = cf[1:].copy()
cf_pos

In [ ]:
cf_pos[0] = 70
cf_pos

In [ ]:
cf

12. Calculate the __total sum__ over all cashflows of cf!

In [ ]:
# run the cell
cf = np.array([-500, 50, 80, 120, 150, 200])
cf

In [ ]:
cf.sum()

13. Return the __highest Value__ of cf!

In [ ]:
cf.max()

14. Calculate the __cumulative cashflows__ for cf!

In [ ]:
cf.cumsum()

15. Assume the following list: [3, 10, 6, 45, 100]. Calculate the __square root__ for all elements in the list. 

In [ ]:
np.sqrt([3, 10, 6, 45, 100])

Assume the following stock prices:

In [ ]:
# run the cell!
a = np.array([0.34, 43.56, 32.12, 67.43, 0.87, 9.87])
a

16. __Filter__ a for all penny stocks! (price less than 1)

In [ ]:
a[a < 1]

(result: array([0.34, 0.87]))