# Appendix 3: Python Libraries Crash Course

## Part 2: Multi-Dimensional Numpy Arrays

### Nested Lists

In [ ]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [ ]:
all_proj = [project_1, project_2, project_3]

In [ ]:
all_proj

In [ ]:
type(all_proj)

In [ ]:
len(all_proj)

In [ ]:
all_proj[0]

In [ ]:
all_proj[2]

In [ ]:
all_proj[-1]

In [ ]:
all_proj[:2]

In [ ]:
all_proj[-2:]

In [ ]:
all_proj[0][0]

In [ ]:
all_proj[:][0]

In [ ]:
I0 = []
for proj in all_proj:
    I0.append(proj[0])

In [ ]:
I0

### 2-dim Numpy Arrays

In [ ]:
import numpy as np

In [ ]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]
nl = [cf1, cf2, cf3]

In [ ]:
nl

In [ ]:
np.array(nl)

In [ ]:
cfs = np.array(nl)

In [ ]:
cfs

In [ ]:
type(cfs)

In [ ]:
cfs.shape

In [ ]:
cfs[0]

In [ ]:
cfs[-1]

In [ ]:
cfs[1:]

In [ ]:
cfs[0][0]

In [ ]:
cfs[0, 0]

### Slicing 2-dim Numpy Arrays (Part 1)

In [ ]:
import numpy as np

In [ ]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [ ]:
cfs = np.array([cf1, cf2, cf3])
cfs

In [ ]:
cfs.shape

In [ ]:
cfs[:, 0]

In [ ]:
cfs[:, -1]

In [ ]:
cfs[:,:2]

In [ ]:
cfs[2, 1:]

In [ ]:
cfs

In [ ]:
cfs[1:, :2]

In [ ]:
cfs[-2:, :-4]

In [ ]:
project_1 = [-200, 20, 50, 70, 100, 50,0,0]
project_2 = [-50, 10, 25, 25, 50,0,0,0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [ ]:
array = np.array([project_1, project_2, project_3]) # no longer working

In [ ]:
array

In [ ]:
#array.shape

In [ ]:
# array[:, 0]

In [ ]:
project_1 = np.array([-200, 20, 50, 70, 100, 50, 0, 0])
project_2 = np.array([-50, 10, 25, 25, 50, 0, 0, 0])
project_3 = np.array([-1000, 200, 200, 300, 500, 500, 750, 250])

In [ ]:
projects = np.array([project_1, project_2, project_3])

In [ ]:
projects

In [ ]:
# Inhomogene Arrays lassen sich mittels np.pad() automatisch mit Nullen auffülen, damit sie dieselben Längen haben

projects123 = [[-200, 20, 50, 70, 100, 50], [-50, 10, 25, 25, 50], [-1000, 200, 200, 300, 500, 500, 750, 250]]
projects = np.array([np.pad(p, (0, 8-len(p))) for p in projects123])
projects

In [ ]:
projects.shape

In [ ]:
projects[:, 0]

In [ ]:
project_1 = np.array([-200, 20, 50, 70, 100, 50])

In [ ]:
project_1.resize(8)

In [ ]:
project_1

### Slicing 2-dim Numpy Arrays (Part 2)

In [ ]:
import numpy as np

In [ ]:
cf1 = np.array([-200, 20, 50, 70, 100, 50])
cf2 = np.array([-150, 25, 60, 50, 50, 40])
cf3 = np.array([-250, 10, 25, 50, 125, 200])

In [ ]:
cfs = np.array([cf1, cf2, cf3])
cfs

In [ ]:
cf1[[0, 3, -1]]

In [ ]:
cfs[[0,-1], 0]

In [ ]:
cfs[0, [0, 2, -1]]

### Recap: Changing Elements in a Numpy Array / slice

In [97]:
import numpy as np

In [98]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [99]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [100]:
cfs[:, 0] = -200

In [101]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-200,   25,   60,   50,   50,   40],
       [-200,   10,   25,   50,  125,  200]])

In [102]:
cfs[:, 0] = cfs[:, 0] - 10

In [103]:
cfs

array([[-210,   20,   50,   70,  100,   50],
       [-210,   25,   60,   50,   50,   40],
       [-210,   10,   25,   50,  125,  200]])

In [118]:
cfs[:, 0] = [-200, -150, -250]

In [119]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150, -180,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [120]:
I0s = cfs[:, 0]
I0s

array([-200, -150, -250])

In [121]:
I0s[0] = -180
I0s

array([-180, -150, -250])

In [122]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150, -180,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [123]:
cf5 = cfs[:, -1].copy()
cf5

array([ 50,  40, 200])

In [124]:
cf5[-1] = 150
cf5

array([ 50,  40, 150])

In [125]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150, -180,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

### Row- and Column wise operations

In [126]:
import numpy as np
np.set_printoptions(precision=2, suppress= True)

In [127]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [128]:
projects = np.array([project_1, project_2, project_3])

In [129]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [130]:
np.sum(projects)

np.int64(1850)

In [131]:
np.sum(projects, axis = 0)

array([-1250,   230,   275,   395,   650,   550,   750,   250])

In [132]:
np.sum(projects, axis = 1)

array([  90,   60, 1700])

In [133]:
np.cumsum(projects, axis = 1)

array([[ -200,  -180,  -130,   -60,    40,    90,    90,    90],
       [  -50,   -40,   -15,    10,    60,    60,    60,    60],
       [-1000,  -800,  -600,  -300,   200,   700,  1450,  1700]])

In [137]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [134]:
np.mean(projects, axis = 1)

array([ 11.25,   7.5 , 212.5 ])

In [135]:
np.mean(projects, axis = 0)

array([-416.66666667,   76.66666667,   91.66666667,  131.66666667,
        216.66666667,  183.33333333,  250.        ,   83.33333333])

In [136]:
np.mean(projects, axis = 1)

array([ 11.25,   7.5 , 212.5 ])

In [ ]:
np.mean(projects)