In [ ]:
from numpy import dtype
from pyparsing import countedArray

my_list=[1,2,3,'four',5,6,7]

In [ ]:
for i in my_list:
    try:
        result=10+i
    except Exception as e:
        print(f'{i} is not a number', end='  |  ')
        print(e,end='  |  ')
        #break
    else: # only if no error occured
        print(result,end='|')
        print(f'{i} is not a valid input', end='  |  ')
    finally: # in any case
        print('Valid or not valid, it doesn´t matter!')

In [10]:
import numpy as np
import time


max_attempts=8
success=False
wait=3 # initial waiting period: 3 second
wait_increase=5 # waiting period increase in seconds
attempt=0
while True:
    try:
        result=1/np.random.randint(0,1)
    except Exception as e:
        print(e,end='  /  ')
    else:
        print(result,end='  |  ')
        success=True
        break # stop when it worked
    finally:
        attempt+=1
        print(f'Attempt: {attempt}')
        if success==False:
            if attempt>=max_attempts: # if max_attempts is reached
                print('Programm stopped: max_attempts reached!')
                break
            else: # if we haven´t reached max_attempts, waitt before we start the next try
                time.sleep(wait)
                wait+=wait_increase # increase waiting time

division by zero  /  Attempt: 1
division by zero  /  Attempt: 2
division by zero  /  Attempt: 3
division by zero  /  Attempt: 4
division by zero  /  Attempt: 5
division by zero  /  Attempt: 6
division by zero  /  Attempt: 7
division by zero  /  Attempt: 8
Programm stopped: max_attempts reached!


In [12]:
name = "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch"
'c' and 'e' in name

True

In [14]:
my_list = [5, 8, 11, 7, 6, 2]

if sum(my_list) > 40:
    print("Greater than 40")
elif sum(my_list) < 40:
    print("Less than 40")
else:
    print("Equal to 40")


Less than 40


In [28]:
import numpy as np
my_list = [3, 4, 6, 8, 6]
my_array=np.array(my_list)
my_array=my_array+10
print(my_array)

[13 14 16 18 16]


In [29]:
import numpy as np
print(np.array([3, 4, 6, 8, 6]) + 10)


[13 14 16 18 16]


In [30]:
import numpy as np
arr = np.array([3, 4, 6, 8, 6]) + 10
print(arr)


[13 14 16 18 16]


In [2]:
import numpy as np
arr = np.add(np.array([3, 4, 6, 8, 6]), 10)
print(arr)


[13 14 16 18 16]


In [1]:
PV=100
f=1.03
n=2

In [5]:
PV*np.power(f,n)

np.float64(106.08999999999999)

In [6]:
cf=[50,100,120,150,200,300]

In [7]:
cf

[50, 100, 120, 150, 200, 300]

In [8]:
cf_array=np.array(cf)
cf_array

array([ 50, 100, 120, 150, 200, 300])

In [9]:
type(cf_array)

numpy.ndarray

In [12]:
cf_array*2


array([100, 200, 240, 300, 400, 600])

In [13]:
cf_array-50


array([  0,  50,  70, 100, 150, 250])

In [14]:
cf_array.dtype

dtype('int64')

In [15]:
type(cf_array)

numpy.ndarray

In [16]:
cf=[50,100,120,150,200,300]
cf

[50, 100, 120, 150, 200, 300]

In [17]:
cf=[50,100,120,150,200,300]
cf[2:3]

[120]

In [18]:
cf=[50,100,120,150,200,300]
cf[:1]

[50]

In [19]:
cf=[50,100,120,150,200,300]
cf[1:]

[100, 120, 150, 200, 300]

In [20]:
cf=[50,100,120,150,200,300]
cf[4:]

[200, 300]

In [21]:
cf=[50,100,120,150,200,300]
cf[-1]

300

In [23]:
cf=[50,100,120,150,200,300]
cf[:-1]

[50, 100, 120, 150, 200]

In [24]:
cf=[50,100,120,150,200,300]
cf[1:-1]

[100, 120, 150, 200]

In [25]:
cf=[50,100,120,150,200,300]
cf[::]

[50, 100, 120, 150, 200, 300]

In [26]:
cf=[50,100,120,150,200,300]
cf[:1:]

[50]

In [4]:
cf=[50,100,120,150,200,300]
cf[1:2]

[100]

In [5]:
# Slice cf from the 3rd (incl.) to the 5th (incl.) element
cf=[1,2,3,4,5,6,7]
cf[2:5]

[3, 4, 5]

In [6]:
# PV with vectorized Numpy Code
#
# Calculate the PV of the following cashflows with vectorized Numpy Code. Print the final PV!
#
# - 300 USD in t1,
#
# - 500 USD in t2,
#
# - 1000 USD in t3,
#
# - 2000 USD in t4
#
# The required rate of return (Cost of Capital) is 6% p.a.

import numpy as np

cf = np.array([300, 500, 1000, 2000])



In [ ]:
import numpy as np
cf = np.array([300, 500, 1000, 2000])  # Cashflows in t=1 bis t=4
r = 0.06  # Required rate of return
t = np.arange(1, 5)  # Zeiträume
pv_factors = (1 + r) ** -t  # Diskontierungsfaktoren
pv = np.sum(cf * pv_factors)  # Vektorisierte PV-Berechnung
print(pv)


In [1]:
import numpy as np

my_array = ([3.435, 6.45464, 7.56, 8.45643, 5.6765])

np.round(my_array, decimals=2)

array([3.44, 6.45, 7.56, 8.46, 5.68])

### Changing Elements in Numpy Arrays & Mutability

In [2]:
cf = np.array([100, 10, 20, 50, 30, 25])

In [3]:
cf[0] = 95

In [4]:
cf

array([95, 10, 20, 50, 30, 25])

In [5]:
cf[1:] = [40, 40, 40, 40, 40]

In [6]:
cf

array([95, 40, 40, 40, 40, 40])

In [7]:
cf[1:] = 45

In [8]:
cf

array([95, 45, 45, 45, 45, 45])

In [9]:
cf + 20

array([115,  65,  65,  65,  65,  65])

In [10]:
cf

array([95, 45, 45, 45, 45, 45])

In [11]:
cf1 = np.array([100, 10, 20, 50, 30, 25])
cf1

array([100,  10,  20,  50,  30,  25])

In [12]:
cf2 = cf1

In [13]:
cf1[0] = 95
cf1

array([95, 10, 20, 50, 30, 25])

In [14]:
cf2

array([95, 10, 20, 50, 30, 25])

In [15]:
cf1 = np.array([100, 10, 20, 50, 30, 25])
cf1

array([100,  10,  20,  50,  30,  25])

In [16]:
cf2 = cf1[:]
cf2

array([100,  10,  20,  50,  30,  25])

In [17]:
cf1[0] = 95
cf1

array([95, 10, 20, 50, 30, 25])

In [18]:
cf2

array([95, 10, 20, 50, 30, 25])

In [19]:
cf1 = np.array([100, 10, 20, 50, 30, 25])
cf1

array([100,  10,  20,  50,  30,  25])

In [20]:
cf2 = cf1.copy()

In [21]:
cf1[0] = 95
cf1

array([95, 10, 20, 50, 30, 25])

In [22]:
cf2

array([100,  10,  20,  50,  30,  25])